//! Vendored OTLP protobuf types, generated by `scripts/otel-proto-gen.sh`.
//! The nesting mirrors the proto packages because the generated code
//! refers to its neighbors as `super::super::…`. Crate-private so prost
//! types stay out of the public API.
#![allow(dead_code, missing_docs, clippy::all, clippy::pedantic, rustdoc::all)]

pub mod opentelemetry {
    pub mod proto {
        pub mod common {
            pub mod v1 {
                include!("opentelemetry.proto.common.v1.rs");
            }
        }
        pub mod resource {
            pub mod v1 {
                include!("opentelemetry.proto.resource.v1.rs");
            }
        }
        pub mod trace {
            pub mod v1 {
                include!("opentelemetry.proto.trace.v1.rs");
            }
        }
        pub mod logs {
            pub mod v1 {
                include!("opentelemetry.proto.logs.v1.rs");
            }
        }
        pub mod collector {
            pub mod trace {
                pub mod v1 {
                    include!("opentelemetry.proto.collector.trace.v1.rs");
                }
            }
            pub mod logs {
                pub mod v1 {
                    include!("opentelemetry.proto.collector.logs.v1.rs");
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::opentelemetry::proto::collector::logs::v1::ExportLogsServiceRequest;
    use super::opentelemetry::proto::collector::trace::v1::ExportTraceServiceRequest;
    use super::opentelemetry::proto::common::v1::any_value::Value as Av;
    use prost::Message;

    /// Hand-encoded without a protobuf library. One span: trace id 01..10,
    /// span id a1..a8, name "chat", kind 3, start 1000, end 2000, attributes
    /// k="v" and n=42, status {message "boom", code 2}, under resource
    /// attribute svc="x" and scope {name "s", version "1"}.
    const TRACES_HEX: &str = "0a6d0a0c0a0a0a0373766312030a0178125d0a060a017312013112530a100102030405060708090a0b0c0d0e0f101208a1a2a3a4a5a6a7a82a0463686174300339e80300000000000041d0070000000000004a080a016b12030a01764a070a016e1202182a7a081204626f6f6d1802";
    /// One log record: time 5, severity 9, body "hi", attribute a=true,
    /// the same trace and span ids, event name "gen_ai.choice"; same
    /// resource and scope.
    const LOGS_HEX: &str = "0a5f0a0c0a0a0a0373766312030a0178124f0a060a0173120131124509050000000000000010092a040a02686932070a0161120210014a100102030405060708090a0b0c0d0e0f105208a1a2a3a4a5a6a7a8620d67656e5f61692e63686f696365";

    fn unhex(s: &str) -> Vec<u8> {
        (0..s.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
            .collect()
    }

    #[test]
    fn traces_known_answer_decodes_and_reencodes_byte_identically() {
        let bytes = unhex(TRACES_HEX);
        let req = ExportTraceServiceRequest::decode(bytes.as_slice()).unwrap();
        let span = &req.resource_spans[0].scope_spans[0].spans[0];
        assert_eq!(span.trace_id, (1..=16).collect::<Vec<u8>>());
        assert_eq!(
            span.span_id,
            [0xa1, 0xa2, 0xa3, 0xa4, 0xa5, 0xa6, 0xa7, 0xa8]
        );
        assert_eq!(span.name, "chat");
        assert_eq!(
            (
                span.kind,
                span.start_time_unix_nano,
                span.end_time_unix_nano
            ),
            (3, 1000, 2000)
        );
        assert_eq!(
            span.attributes[1].value.as_ref().unwrap().value,
            Some(Av::IntValue(42))
        );
        assert_eq!(span.status.as_ref().unwrap().code, 2);
        assert_eq!(req.encode_to_vec(), bytes);
    }

    #[test]
    fn logs_known_answer_decodes_and_reencodes_byte_identically() {
        let bytes = unhex(LOGS_HEX);
        let req = ExportLogsServiceRequest::decode(bytes.as_slice()).unwrap();
        let rec = &req.resource_logs[0].scope_logs[0].log_records[0];
        assert_eq!((rec.time_unix_nano, rec.severity_number), (5, 9));
        assert_eq!(rec.event_name, "gen_ai.choice");
        assert_eq!(
            rec.body.as_ref().unwrap().value,
            Some(Av::StringValue("hi".into()))
        );
        assert_eq!(req.encode_to_vec(), bytes);
    }

    #[test]
    fn logs_bytes_fail_the_traces_decode_on_wire_type() {
        // LogRecord field 1 is fixed64; Span field 1 is LEN.
        let err = ExportTraceServiceRequest::decode(unhex(LOGS_HEX).as_slice()).unwrap_err();
        assert!(err.to_string().contains("invalid wire type"), "{err}");
    }
}
