// @generated by scripts/otel-proto-gen.sh; do not edit.
// Source: open-telemetry/opentelemetry-proto v1.11.0 (790608c4d51e6ffc12210b541e8514cbed9e91a4).
// Generator: prost-build 0.14.4, libprotoc 36.1, comments disabled.
// Upstream notice of opentelemetry/proto/resource/v1/resource.proto, retained verbatim:
//
// Copyright 2019, OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Resource {
    #[prost(message, repeated, tag = "1")]
    pub attributes: ::prost::alloc::vec::Vec<super::super::common::v1::KeyValue>,
    #[prost(uint32, tag = "2")]
    pub dropped_attributes_count: u32,
    #[prost(message, repeated, tag = "3")]
    pub entity_refs: ::prost::alloc::vec::Vec<super::super::common::v1::EntityRef>,
}
