#!/usr/bin/env bash
# Regenerate the vendored OTLP protobuf types in crates/toolpath-otel/src/proto/.
#
# Maintainer-only. Users and CI never run it: the generated files are committed,
# and the crate has no build.rs. Needs git, cargo and protoc (pinned below).
#
# Usage:
#   scripts/otel-proto-gen.sh           regenerate in place
#   scripts/otel-proto-gen.sh --check   regenerate into a temp dir and diff
#
# To move to a new upstream tag: change PROTO_TAG and PROTO_COMMIT (verify the
# commit with `git ls-remote --tags <repo> <tag>`), run the script, review the
# diff, and record the new tag in CHANGELOG.md and docs/agents/formats/otel.md.
set -euo pipefail

readonly PROTO_REPO="https://github.com/open-telemetry/opentelemetry-proto.git"
readonly PROTO_TAG="v1.11.0"
readonly PROTO_COMMIT="790608c4d51e6ffc12210b541e8514cbed9e91a4"
readonly PROTOC_VERSION="libprotoc 36.1"
readonly PROST_BUILD_VERSION="0.14.4"
readonly GENERATED=(
    opentelemetry.proto.collector.logs.v1.rs
    opentelemetry.proto.collector.trace.v1.rs
    opentelemetry.proto.common.v1.rs
    opentelemetry.proto.logs.v1.rs
    opentelemetry.proto.resource.v1.rs
    opentelemetry.proto.trace.v1.rs
)

_root="$(cd "$(dirname "$0")/.." && pwd)"
_dest="${_root}/crates/toolpath-otel/src/proto"
_check=false
if [[ "${1:-}" == "--check" ]]; then
    _check=true
fi

if ! command -v protoc >/dev/null 2>&1; then
    echo "protoc not found; need ${PROTOC_VERSION} (brew install protobuf, or nix shell nixpkgs#protobuf)" >&2
    exit 1
fi
_protoc="$(protoc --version)"
if [[ "${_protoc}" != "${PROTOC_VERSION}" ]]; then
    echo "protoc is '${_protoc}', pinned '${PROTOC_VERSION}'" >&2
    if [[ "${OTEL_PROTO_GEN_ANY_PROTOC:-}" != "1" ]]; then
        exit 1
    fi
    echo "continuing because OTEL_PROTO_GEN_ANY_PROTOC=1" >&2
fi

_work="$(mktemp -d)"
trap 'rm -rf "${_work}"' EXIT

git -c advice.detachedHead=false clone --quiet --depth 1 --branch "${PROTO_TAG}" "${PROTO_REPO}" "${_work}/proto"
_commit="$(git -C "${_work}/proto" rev-parse HEAD)"
if [[ "${_commit}" != "${PROTO_COMMIT}" ]]; then
    echo "${PROTO_TAG} resolves to ${_commit}, pinned ${PROTO_COMMIT}" >&2
    exit 1
fi

mkdir -p "${_work}/raw" "${_work}/out"
cargo run --quiet --locked --release \
    --manifest-path "${_root}/scripts/otel-proto-gen/Cargo.toml" \
    --target-dir "${_work}/target" \
    -- "${_work}/proto" "${_work}/raw"

for _name in "${GENERATED[@]}"; do
    if [[ ! -f "${_work}/raw/${_name}" ]]; then
        echo "generator did not produce ${_name}" >&2
        exit 1
    fi
    # The package's one .proto (opentelemetry.proto.logs.v1.rs <-
    # opentelemetry/proto/logs/v1/*.proto) carries the upstream copyright and
    # license notice; Apache-2.0 section 4(c) asks derived source to keep it.
    _pkg="${_name%.rs}"
    _protos=("${_work}/proto/${_pkg//.//}"/*.proto)
    if [[ ${#_protos[@]} -ne 1 || ! -f "${_protos[0]}" ]]; then
        echo "expected exactly one .proto for ${_name} under ${_pkg//.//}" >&2
        exit 1
    fi
    _notice="$(sed -n '/^\/\//!q; p' "${_protos[0]}")"
    if [[ "${_notice}" != *"Copyright"*"Apache License"* ]]; then
        echo "no upstream copyright/license notice at the top of ${_protos[0]#"${_work}/proto/"}" >&2
        exit 1
    fi
    {
        echo "// @generated by scripts/otel-proto-gen.sh; do not edit."
        echo "// Source: open-telemetry/opentelemetry-proto ${PROTO_TAG} (${PROTO_COMMIT})."
        echo "// Generator: prost-build ${PROST_BUILD_VERSION}, ${_protoc}, comments disabled."
        echo "// Upstream notice of ${_protos[0]#"${_work}/proto/"}, retained verbatim:"
        echo "//"
        echo "${_notice}"
        echo
        cat "${_work}/raw/${_name}"
    } >"${_work}/out/${_name}"
done

# Every generated file in src/proto must be one this script writes; a stale
# file from an older tag would otherwise linger unreviewed.
_extra=()
for _path in "${_dest}"/opentelemetry.*.rs; do
    [[ -e "${_path}" ]] || continue
    _base="$(basename "${_path}")"
    _known=false
    for _name in "${GENERATED[@]}"; do
        if [[ "${_base}" == "${_name}" ]]; then
            _known=true
        fi
    done
    if ! ${_known}; then
        _extra+=("${_base}")
    fi
done
if [[ ${#_extra[@]} -gt 0 ]]; then
    echo "unexpected generated files in ${_dest} (not in GENERATED; delete or list them): ${_extra[*]}" >&2
    exit 1
fi

if ${_check}; then
    _status=0
    for _name in "${GENERATED[@]}"; do
        if ! diff -u "${_dest}/${_name}" "${_work}/out/${_name}"; then
            _status=1
        fi
    done
    if [[ ${_status} -eq 0 ]]; then
        echo "src/proto is up to date with ${PROTO_TAG}"
    fi
    exit "${_status}"
fi

for _name in "${GENERATED[@]}"; do
    cp "${_work}/out/${_name}" "${_dest}/${_name}"
done
echo "regenerated ${#GENERATED[@]} files from ${PROTO_TAG} into ${_dest}"
